### ISSUE TITLE
Cannot get rid of //wand item after I'm done with it

### ISSUE THREAD

**Issue by Senlar** [lordmampf/EcoWorldEdit#2]
I did the //wand command twice and I wanted to get rid of one of the items but couldn't. Could you add a command to get rid of the tool?

**Comment by manureini** [comment]
I just commited 5b0b501cf897654263b1678e9adb1dddc4d556e2 which adds a `//rmwand` command.
Maybe it's useful to have multiple wands in the future. That's why i added a new command
